runtime: nodejs20
env: standard

instance_class: F2  # Choose an appropriate instance class

automatic_scaling:
  min_instances: 1  # Keep at least one instance running
  max_instances: 5  # Adjust as needed


env_variables:
  GCS_BUCKET_NAME: "far-attachements-from-drive"
  NODE_ENV: 'production'

service_account: farwarehousing@far-warehousing.iam.gserviceaccount.com
